---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: koti-deploymentss
spec:
 replicas: 1
 strategy: 
    type: Recreate
 selector: 
   matchLabels: 
     app: koti-kotiss
 template:
  metadata:
   name: koti-kotipodss
   labels:
     app: koti-kotiss	 
  spec: 
    containers:
    - name: koti-kotiss
      image: koteswarararaosairi/k8sma:v12
      imagePullPolicy: Always
      ports:
      - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
 name: koti-servicess
spec:
  type: NodePort
  selector:
   app: koti-kotiss
  ports:
   - port: 3000
     targetPort: 3000
...
